### ISSUE TITLE
which checkpoint?

### ISSUE THREAD

**Issue by toosi** [facebookresearch/jepa-intuitive-physics#2]
Hello,

Thanks for sharing the code for such a cool work. I tried to run the evals on vith16 checkpoint in jepa rep [(config)](https://github.com/facebookresearch/jepa/blob/main/configs/pretrain/vith16.yaml) but I get accuracy of 50% on O1. Which checkpoint do you recommand to test for O1?

Thanks,

**Comment by garridoq** [comment]
Hi,

Thank you for the interesting in our work. The checkpoints that were used in the paper are not released, let me try with the publicaly available model to see if I can get normal performance with it.

**Comment by garridoq** [comment]
I have run the evaluation for the open source V-JEPA vit-h 16 model that you linked, using the following eval config (adapted as the model uses sincos positional embeddings): 
```
pretrain:
  enc_checkpoint_key: encoder
  pred_checkpoint_key: predictor
  model_name: vit_huge
  patch_size: 16
  folder: YOUR_PATH
  checkpoint: vith16.pth.tar
  write_tag: jepa
  use_sdpa: true
  uniform_power: true
  is_causal: false
  pred_is_causal: false
  pred_depth: 12
  tubelet_size: 2
  frames_per_clip: 16
data:
  batch_size: 1
  resolution: 224
  stride_sliding_window: 2
  use_bfloat16: true
  frames_per_clip: 16
  context_lengths: [2,4,6,8,10]
  frame_steps: 2
tag: default
nodes: 1
tasks_per_node: 6
eval_name: intuitive_physics
dataset: intphys
```

This leads to peak performance of 85% on O1, 96% on O2 and 95%on O3 (for the pairwise metric "Relative Accuracy (avg)"). 
Let me know if you are able to reproduce the numbers with this evaluation config.
