### ISSUE TITLE
GRASP Evaluation Issue with V-JEPA checkpoint

### ISSUE THREAD

**Issue by yingShen-ys** [facebookresearch/jepa-intuitive-physics#5]
Thank you for the great work!

I'm currently trying to run the evaluation on the GRASP dataset using the V-JEPA ViT-H/16 checkpoint and config as described in #2. 

I’ve been able to successfully run evaluations on InfLevel and IntPhys using the V-JEPA ViT-H/16 checkpoint and config. 

However, I’m running into the following error when evaluating on GRASP.
```
IndexError: index 1 is out of bounds for dimension 0 with size 1
```

The error occurs at this line in eval.py:

```
File "/path/to/jepa-intuitive-physics/evaluation_code/evals/intuitive_physics/eval.py", line 291, in compute_metrics
    thresh = data1.sort()[0][int(np.ceil(0.90*len(data1)))]
```

Here is the evaluation config I’m using:
```
pretrain:
  enc_checkpoint_key: encoder
  pred_checkpoint_key: predictor
  model_name: vit_huge
  patch_size: 16
  folder: PATH
  checkpoint: vith16.pth.tar
  write_tag: jepa
  use_sdpa: true
  uniform_power: true
  is_causal: false
  pred_is_causal: false
  # use_silu: true
  # wide_silu: false
  pred_depth: 12
  tubelet_size: 2
  frames_per_clip: 16
data:
  batch_size: 1
  resolution: 224
  stride_sliding_window: 2
  use_bfloat16: true
  frames_per_clip: 16
  context_lengths: [2,4,6,8,10]
  frame_steps: 10
tag: default
nodes: 1
tasks_per_node: 8
eval_name: intuitive_physics
dataset: grasp
```

Do I need to modify anything in the config specifically for GRASP? Thank you!
